#!/usr/bin/env python3
"""Generate the launcher icon and the 512² Play listing asset from `mark.py`.

Writes, all of them derived and none of them hand-editable:

    app/src/main/res/drawable/ic_launcher_foreground.xml
    app/src/main/res/drawable/ic_launcher_monochrome.xml
    app/src/main/res/drawable/ic_notification.xml
    app/src/main/res/mipmap-{m,h,xh,xxh,xxx}dpi/ic_launcher{,_round}.webp
    art/play-icon-512.png

`ic_launcher_background.xml` is not written — it is a flat PRIMARY rectangle with no art in it — but
its fillColor is *checked* against `mark.PRIMARY` before anything else runs, because it is otherwise
a second hand-maintained copy of that colour and a recolour silently updating only one of the two is
the failure this script exists beside.

    python3 art/make-launcher-icon.py
"""

import math
import re
from pathlib import Path

from PIL import Image, ImageDraw

import mark

ART = Path(__file__).parent
RES = ART.parent / "app/src/main/res"

CANVAS = 108  # adaptive-icon canvas, in dp
VISIBLE = 72  # the most any launcher shows of it — what the flat assets are cropped to
ART_SIZE = 50  # longest side of the mark — bounded by SAFE_DIAMETER, see below

# A launcher may mask the icon down to a 66dp circle, so anything outside that gets clipped.
# For this mark that is a real constraint rather than a formality: it is nearly square, so at
# 60dp a tall narrow mark might use, its extremities reach 36dp from the
# centre against a 33dp safe radius and a circular launcher would cut them off. 54dp is the
# largest size that puts the whole outline inside the circle — and even shrunk to fit, it
# carries about 19% more ink than the mark it replaces, because a compact silhouette uses the
# canvas that a narrow one wastes. main() asserts the property rather than trusting this note.
SAFE_DIAMETER = 66

DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
SS = 20  # supersample factor for the raster assets

# A notification small icon has no adaptive-icon safe zone to respect — Android draws it as a
# silhouette in a 24dp slot — so the mark is scaled up to fill nearly the whole viewport. At
# ART_SIZE it would be a speck. Expressed as dp of the 108 viewport, then converted to the
# group scale, so changing ART_SIZE cannot silently resize the notification icon with it.
NOTIFICATION_ART = 96

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  The app mark. Original art, declared in art/mark.py and generated by
  art/make-launcher-icon.py — regenerate rather than editing the path data here. The eye is
  a hole in the path, not a painted shape, so it survives the monochrome layer's flat tint.
-->
"""

NOTIFICATION_HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  The launcher's monochrome mark, scaled up to fill a notification icon. Generated by
  art/make-launcher-icon.py — regenerate rather than editing the path data here.

  A notification small icon is drawn as a **silhouette**: Android throws away every colour in
  it and tints the non-transparent pixels, which is why this reuses the monochrome layer's
  path rather than the full-colour launcher art. The scale exists because the adaptive-icon
  path is drawn inside a 108x108 viewport with a large safe zone around it, and dropped into a
  24dp notification slot unchanged the mark would be a speck. The art is already centred on
  (54, 54), so the group needs a scale and no translation.
-->
"""

NOTIFICATION = """{header}<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="108"
    android:viewportHeight="108"
    android:tint="#FFFFFF">
  <group
      android:pivotX="54"
      android:pivotY="54"
      android:scaleX="{scale}"
      android:scaleY="{scale}">
    <path
        android:fillColor="#FFFFFF"
        android:pathData="{data}" />
  </group>
</vector>
"""

VECTOR = """{header}<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
  <path
      android:fillColor="{colour}"
      android:pathData="{data}" />
</vector>
"""


def hex_of(rgb):
    return "#{:02X}{:02X}{:02X}".format(*rgb)


def vector_path_data():
    tf = mark.fit(CANVAS, ART_SIZE)
    return "".join(mark.path_data(e, tf) for e in mark.PARTS)


def render(size, mask_circle=False):
    """The composed icon — coloured ground, light mark — cropped to the visible 72dp."""
    big = CANVAS * SS
    img = Image.new("RGBA", (big, big), mark.PRIMARY + (255,))
    d = ImageDraw.Draw(img)
    tf = mark.fit(CANVAS * SS, ART_SIZE * SS)
    for e in mark.PARTS:
        # On the flat assets the hole is simply painted back to the ground colour; the
        # winding trick only matters where something else shows through.
        colour = (mark.PRIMARY if e.hole else mark.SURFACE) + (255,)
        d.polygon(mark.outline(e, tf), fill=colour)

    inset = (CANVAS - VISIBLE) // 2 * SS
    img = img.crop((inset, inset, big - inset, big - inset)).resize((size, size), Image.LANCZOS)

    if mask_circle:
        mask = Image.new("L", (size * 4, size * 4), 0)
        ImageDraw.Draw(mask).ellipse((0, 0, size * 4 - 1, size * 4 - 1), fill=255)
        img.putalpha(mask.resize((size, size), Image.LANCZOS))
    return img


def check_background():
    """The one colour this script does not write, checked against the one it does.

    `ic_launcher_background.xml` is a flat PRIMARY rectangle with no art in it, so there is nothing
    here to generate — but that leaves the icon's ground as a second, hand-maintained copy of
    `mark.PRIMARY`. Nothing forced the two to agree, and a recolour that updates one and not the
    other produces a mark painted in the new colour on a ground still in the old one. Cheap to
    check, so it is checked rather than documented.
    """
    path = RES / "drawable" / "ic_launcher_background.xml"
    found = re.search(r'android:fillColor="(#[0-9A-Fa-f]{6})"', path.read_text())
    if not found:
        raise SystemExit(f"{path}: no fillColor found — has the file's shape changed?")
    want, got = hex_of(mark.PRIMARY).upper(), found.group(1).upper()
    if want != got:
        raise SystemExit(
            f"{path}: fillColor is {got}, but mark.PRIMARY is {want}.\n"
            f"This file is not generated. Set the fillColor to {want} by hand and re-run."
        )
    return f"ground {got} matches mark.PRIMARY"


def main():
    print(check_background())
    data = vector_path_data()
    written = []

    for name, colour in (
        ("ic_launcher_foreground", hex_of(mark.SURFACE)),
        ("ic_launcher_monochrome", "#FFFFFF"),
    ):
        path = RES / "drawable" / f"{name}.xml"
        path.write_text(VECTOR.format(header=HEADER, colour=colour, data=data))
        written.append(path)

    notification = RES / "drawable" / "ic_notification.xml"
    notification.write_text(NOTIFICATION.format(
        header=NOTIFICATION_HEADER,
        scale=f"{NOTIFICATION_ART / ART_SIZE:.3f}",
        data=data,
    ))
    written.append(notification)

    for density, size in DENSITIES.items():
        for name, circle in (("ic_launcher", False), ("ic_launcher_round", True)):
            path = RES / f"mipmap-{density}" / f"{name}.webp"
            render(size, mask_circle=circle).save(path, "WEBP", lossless=True, quality=100)
            written.append(path)

    play = ART / "play-icon-512.png"
    render(512).convert("RGB").save(play, "PNG", optimize=True)  # Play rejects alpha
    written.append(play)

    x0, y0, x1, y1 = mark.bounds()
    w, h = x1 - x0, y1 - y0
    scale = ART_SIZE / max(w, h)

    # Measure how far the art itself reaches, not the bounding box: the box's corners are
    # empty for any compact mark, so a half-diagonal reports a clipping problem that
    # isn't there — and would have hidden the real one when the mark changed shape.
    tf = mark.fit(CANVAS, ART_SIZE)
    reach = max(
        math.hypot(px - CANVAS / 2, py - CANVAS / 2)
        for e in mark.PARTS
        if not e.hole
        for px, py in mark.outline(e, tf)
    )
    safe = SAFE_DIAMETER / 2
    print(f"mark {w:.0f}x{h:.0f} -> {w * scale:.1f}x{h * scale:.1f}dp on a {CANVAS}dp canvas")
    print(f"art reaches {reach:.1f}dp from centre vs {safe:.0f}dp safe radius"
          f" — {'inside' if reach <= safe else 'CLIPPED by a circular mask'}")
    print(f"path data {len(data)} chars")
    for p in written:
        print(f"  {p.relative_to(ART.parent)}")


if __name__ == "__main__":
    main()
