#!/usr/bin/env python3
"""Generate the launcher icon and the 512² Play listing asset from `mark.py`.

Writes, all of them derived and none of them hand-editable:

    app/src/main/res/drawable/ic_launcher_foreground.xml
    app/src/main/res/drawable/ic_launcher_monochrome.xml
    app/src/main/res/drawable/ic_notification.xml
    app/src/main/res/mipmap-{m,h,xh,xxh,xxx}dpi/ic_launcher{,_round}.webp
    art/play-icon-512.png

    app/src/main/res/drawable/ic_launcher_background.xml

`ic_launcher_background.xml` **used to be the one file here that was not generated** — a flat
rectangle in a colour hand-copied from `mark.PRIMARY`, with a check in front of it because nothing
made the two agree. The ground is a gradient now, so there is real art in that file and no honest
way to hand-maintain it: it is generated from `mark.ground()` like everything else, and the second
copy the check existed to police is simply gone.

    python3 art/make-launcher-icon.py
"""

import math
from pathlib import Path

from PIL import Image, ImageDraw

import mark

ART = Path(__file__).parent
RES = ART.parent / "app/src/main/res"

CANVAS = 108  # adaptive-icon canvas, in dp
VISIBLE = 72  # the most any launcher shows of it — what the flat assets are cropped to
ART_SIZE = 60  # longest side of the mark — bounded by SAFE_DIAMETER, see below

# A launcher may mask the icon down to a 66dp circle, so anything outside that gets clipped.
# The mark *is* a disc, so its reach from the centre is simply its radius and nothing pokes
# out at the corners: 66dp would sit exactly on the safe circle, and 60dp is the keyline
# Android's own guidance gives a full-bleed circular icon — a 3dp ring of ground all round,
# which is what stops the disc reading as a bitten-off edge under a circular mask.
# main() asserts the property rather than trusting this note.
SAFE_DIAMETER = 66

DENSITIES = {"mdpi": 48, "hdpi": 72, "xhdpi": 96, "xxhdpi": 144, "xxxhdpi": 192}
SS = 20  # supersample factor for the raster assets

# The gradient ground is computed on a coarse grid and scaled up. Supersampling exists for the
# *edges* of the mark, and a gradient has no edges to alias — computing it at 2160² per density
# instead would be a few million Python-level pixels for a result the eye cannot tell apart.
GROUND_GRID = 216
GRADIENT_STOPS = 9  # colour stops sampled off mark.ground() for the VectorDrawable

# A notification small icon has no adaptive-icon safe zone to respect — Android draws it as a
# silhouette in a 24dp slot — so the mark is scaled up to fill nearly the whole viewport. At
# ART_SIZE it would be a speck. Expressed as dp of the 108 viewport, then converted to the
# group scale, so changing ART_SIZE cannot silently resize the notification icon with it.
NOTIFICATION_ART = 96

HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  The app mark. Original art, declared in art/mark.py and generated by
  art/make-launcher-icon.py — regenerate rather than editing the path data here. The crescent
  is a hole in the path, not a painted shape, so it survives the monochrome layer's tint.
-->
"""

NOTIFICATION_HEADER = """<?xml version="1.0" encoding="utf-8"?>
<!--
  The launcher's monochrome mark, scaled up to fill a notification icon. Generated by
  art/make-launcher-icon.py — regenerate rather than editing the path data here.

  A notification small icon is drawn as a **silhouette**: Android throws away every colour in
  it and tints the non-transparent pixels, which is why this reuses the monochrome layer's
  path rather than the full-colour launcher art. The scale exists because the adaptive-icon
  path is drawn inside a 108x108 viewport with a large safe zone around it, and dropped into a
  24dp notification slot unchanged the mark would be a speck. The art is already centred on
  (54, 54), so the group needs a scale and no translation.
-->
"""

NOTIFICATION = """{header}<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="108"
    android:viewportHeight="108"
    android:tint="#FFFFFF">
  <group
      android:pivotX="54"
      android:pivotY="54"
      android:scaleX="{scale}"
      android:scaleY="{scale}">
    <path
        android:fillColor="#FFFFFF"
        android:pathData="{data}" />
  </group>
</vector>
"""

BACKGROUND = """<?xml version="1.0" encoding="utf-8"?>
<!--
  The adaptive icon's back layer: the app's night with the amber banked low, which is the same
  horizon art/make-feature-graphic.py draws. Generated by art/make-launcher-icon.py from
  mark.ground() — regenerate rather than editing the stops here.

  A themed launcher (API 33+) ignores this layer entirely and tints the monochrome one flat, so
  the gradient is what a *standard* icon shows and nothing here is load-bearing for theming.
-->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:aapt="http://schemas.android.com/aapt"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
  <path android:pathData="M0,0h108v108h-108z">
    <aapt:attr name="android:fillColor">
      <gradient
          android:type="radial"
          android:centerX="{cx}"
          android:centerY="{cy}"
          android:gradientRadius="{radius}">
{stops}
      </gradient>
    </aapt:attr>
  </path>
</vector>
"""

VECTOR = """{header}<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp"
    android:height="108dp"
    android:viewportWidth="108"
    android:viewportHeight="108">
  <path
      android:fillColor="{colour}"
      android:pathData="{data}" />
</vector>
"""


def hex_of(rgb):
    return "#{:02X}{:02X}{:02X}".format(*rgb)


def vector_path_data():
    tf = mark.fit(CANVAS, ART_SIZE)
    return "".join(mark.path_data(e, tf) for e in mark.PARTS)


def ground_image(size):
    """The gradient ground, on the full 108dp canvas, at `size` px square.

    Computed on GROUND_GRID and scaled up — see the constant for why that is not a shortcut.
    """
    grid = Image.new("RGB", (GROUND_GRID, GROUND_GRID))
    px = grid.load()
    gx, gy = mark.GLOW_AT
    for y in range(GROUND_GRID):
        for x in range(GROUND_GRID):
            offset = math.hypot(x / GROUND_GRID - gx, y / GROUND_GRID - gy) / mark.GLOW_RADIUS
            px[x, y] = mark.ground(offset)
    return grid.resize((size, size), Image.BICUBIC)


def background_vector():
    """`ic_launcher_background.xml`: the ground as a VectorDrawable radial gradient.

    The stops are *sampled off `mark.ground()`* rather than written out, so the vector and the
    raster mipmaps are the same curve rendered twice rather than two descriptions of it. A radial
    gradient interpolates linearly between stops and `mark.ground()` is a power curve, so the
    stop count is what buys the accuracy — GRADIENT_STOPS of them across the radius is well inside
    a rounding error at any density a launcher asks for.

    Note the units: `centerX/Y` and `gradientRadius` are in **viewport** coordinates (the 108dp
    canvas), while mark.GLOW_AT and GLOW_RADIUS are fractions of it.
    """
    gx, gy = mark.GLOW_AT
    stops = "\n".join(
        f'          <item android:offset="{i / (GRADIENT_STOPS - 1):.4g}"'
        f' android:color="{hex_of(mark.ground(i / (GRADIENT_STOPS - 1)))}" />'
        for i in range(GRADIENT_STOPS)
    )
    return BACKGROUND.format(
        cx=f"{gx * CANVAS:g}",
        cy=f"{gy * CANVAS:g}",
        radius=f"{mark.GLOW_RADIUS * CANVAS:g}",
        stops=stops,
    )


def render(size, mask_circle=False):
    """The composed icon — gradient ground, light mark — cropped to the visible 72dp."""
    big = CANVAS * SS
    img = ground_image(big).convert("RGBA")

    # The mark goes on its own layer so the crescent can be punched to full transparency and let
    # the ground show through. It used to be painted back in the ground's colour, which worked
    # only while the ground *had* one colour — over a gradient that would match at exactly one
    # height and read as a flat patch everywhere else.
    layer = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    tf = mark.fit(big, ART_SIZE * SS)
    for e in mark.PARTS:
        if not e.hole:
            d.polygon(mark.outline(e, tf), fill=mark.SURFACE + (255,))
    for e in mark.PARTS:
        if e.hole:
            d.polygon(mark.outline(e, tf), fill=(0, 0, 0, 0))
    img.alpha_composite(layer)

    inset = (CANVAS - VISIBLE) // 2 * SS
    img = img.crop((inset, inset, big - inset, big - inset)).resize((size, size), Image.LANCZOS)

    if mask_circle:
        mask = Image.new("L", (size * 4, size * 4), 0)
        ImageDraw.Draw(mask).ellipse((0, 0, size * 4 - 1, size * 4 - 1), fill=255)
        img.putalpha(mask.resize((size, size), Image.LANCZOS))
    return img


def main():
    data = vector_path_data()
    written = []

    background = RES / "drawable" / "ic_launcher_background.xml"
    background.write_text(background_vector())
    written.append(background)

    for name, colour in (
        ("ic_launcher_foreground", hex_of(mark.SURFACE)),
        ("ic_launcher_monochrome", "#FFFFFF"),
    ):
        path = RES / "drawable" / f"{name}.xml"
        path.write_text(VECTOR.format(header=HEADER, colour=colour, data=data))
        written.append(path)

    notification = RES / "drawable" / "ic_notification.xml"
    notification.write_text(NOTIFICATION.format(
        header=NOTIFICATION_HEADER,
        scale=f"{NOTIFICATION_ART / ART_SIZE:.3f}",
        data=data,
    ))
    written.append(notification)

    for density, size in DENSITIES.items():
        for name, circle in (("ic_launcher", False), ("ic_launcher_round", True)):
            path = RES / f"mipmap-{density}" / f"{name}.webp"
            render(size, mask_circle=circle).save(path, "WEBP", lossless=True, quality=100)
            written.append(path)

    play = ART / "play-icon-512.png"
    render(512).convert("RGB").save(play, "PNG", optimize=True)  # Play rejects alpha
    written.append(play)

    x0, y0, x1, y1 = mark.bounds()
    w, h = x1 - x0, y1 - y0
    scale = ART_SIZE / max(w, h)

    # Measure how far the art itself reaches, not the bounding box: the box's corners are
    # empty for any compact mark, so a half-diagonal reports a clipping problem that
    # isn't there — and would have hidden the real one when the mark changed shape.
    tf = mark.fit(CANVAS, ART_SIZE)
    reach = max(
        math.hypot(px - CANVAS / 2, py - CANVAS / 2)
        for e in mark.PARTS
        if not e.hole
        for px, py in mark.outline(e, tf)
    )
    safe = SAFE_DIAMETER / 2
    print(f"mark {w:.0f}x{h:.0f} -> {w * scale:.1f}x{h * scale:.1f}dp on a {CANVAS}dp canvas")
    print(f"art reaches {reach:.1f}dp from centre vs {safe:.0f}dp safe radius"
          f" — {'inside' if reach <= safe else 'CLIPPED by a circular mask'}")
    print(f"path data {len(data)} chars")
    for p in written:
        print(f"  {p.relative_to(ART.parent)}")


if __name__ == "__main__":
    main()
