package app.gloam.ui.settings

/**
 * One sentence to verify: read it, then answer whether it is true.
 *
 * **Sentence verification rather than reading aloud**, which is what MNREAD does. There is nobody
 * here to listen and time a reader, so the tap stands in for them. It also makes skimming visible
 * rather than rewarded: a sentence that was not read is answered at chance.
 */
data class ReadingSentence(
    val text: String,
    val isTrue: Boolean,
)

/**
 * The two banks the reading test draws from, one per language the app ships.
 *
 * **Written to keep everything except legibility out of the reaction time**, so that the only thing
 * that differs between conditions is the colour of the light:
 *
 * - common knowledge only, so the answer is known the moment the sentence is read;
 * - no negations and no numbers to work out, both of which slow verification on their own;
 * - four to seven words, so no sentence is much longer to read than another;
 * - half true and half false, and a false one is plainly false rather than arguable.
 *
 * Nothing about sleep, eyes or health, for the same reason the shipped copy avoids it.
 *
 * Hardcoded here rather than in `strings.xml` because this is debug apparatus (`DebugSettings.kt`
 * explains the seam), and a test stimulus must not change when someone improves a translation.
 */
object ReadingSentences {
    fun bank(polish: Boolean): List<ReadingSentence> = if (polish) POLISH else ENGLISH

    private fun t(text: String) = ReadingSentence(text, isTrue = true)

    private fun f(text: String) = ReadingSentence(text, isTrue = false)

    private val ENGLISH =
        listOf(
            t("Fish can swim in water."),
            t("Snow is cold to touch."),
            t("Birds have feathers and wings."),
            t("The sun rises in the morning."),
            t("Bread is baked in an oven."),
            t("Cows give milk to farmers."),
            t("A week has seven days."),
            t("Lemons taste sour."),
            t("Trees grow from seeds."),
            t("Rain falls from the clouds."),
            t("A car needs fuel to run."),
            t("Honey is made by bees."),
            t("Dogs like to chase balls."),
            t("Ice melts in warm weather."),
            t("A clock shows the time."),
            t("Apples grow on trees."),
            t("Shoes are worn on feet."),
            t("The sea tastes salty."),
            t("A key opens a lock."),
            t("Grass is usually green."),
            t("Children go to school to learn."),
            t("Soup is eaten with a spoon."),
            t("Winter is colder than summer."),
            t("A pilot flies a plane."),
            t("Cats have long whiskers."),
            t("Books are made of pages."),
            t("A bicycle has two wheels."),
            t("Coffee is often served hot."),
            t("Stars shine at night."),
            t("A doctor helps sick people."),
            t("An orange is a fruit."),
            t("Fire gives off heat."),
            t("A chair is for sitting."),
            t("Mountains are higher than hills."),
            t("Umbrellas keep people dry."),
            t("Horses can run fast."),
            t("A letter goes in an envelope."),
            t("Milk is white."),
            t("Frogs can jump."),
            t("A baker makes bread."),
            t("Candles give light."),
            t("The moon moves around the earth."),
            t("Ducks swim on ponds."),
            t("Gloves keep hands warm."),
            t("A train runs on rails."),
            t("Carrots grow in the ground."),
            t("A hammer drives in nails."),
            t("Summer days are long."),
            t("Owls hunt at night."),
            t("Boats float on water."),
            t("Tea is made with hot water."),
            t("A piano has keys."),
            t("Sheep have thick wool."),
            t("Wood comes from trees."),
            t("A mirror shows your face."),
            t("Ripe bananas are yellow."),
            t("Farmers grow crops in fields."),
            t("Wind can move the leaves."),
            t("A kettle boils water."),
            t("Scissors cut paper."),
            f("Fish climb tall trees."),
            f("Snow is hot to touch."),
            f("Cows fly over houses."),
            f("The sun rises at midnight."),
            f("Bread is baked in a fridge."),
            f("A week has ten days."),
            f("Lemons taste like chocolate."),
            f("Rain falls up from the ground."),
            f("Honey is made by snakes."),
            f("Ice freezes in a hot oven."),
            f("Shoes are worn on hands."),
            f("Soup is eaten with a key."),
            f("Grass is usually purple."),
            f("A bicycle has nine wheels."),
            f("Stars shine only at noon."),
            f("Mountains are lower than puddles."),
            f("Horses live at the bottom of the sea."),
            f("Milk is bright blue."),
            f("Frogs speak fluent French."),
            f("Candles make a room cold."),
            f("Ducks are made of stone."),
            f("Gloves are worn on ears."),
            f("A train sails across the sky."),
            f("Carrots grow on clouds."),
            f("Owls read the newspaper."),
            f("Boats drive along the motorway."),
            f("Tea is made with sand."),
            f("A piano is a fruit."),
            f("Sheep have long trunks."),
            f("Wood is made from glass."),
            f("Ripe bananas are blue."),
            f("Wind is a kind of cheese."),
            f("A kettle freezes water."),
            f("Cats lay eggs in nests."),
            f("Books are made of soup."),
            f("A chair is for swimming."),
            f("Children ride whales to school."),
            f("Winter is warmer than summer."),
            f("A pilot flies a bathtub."),
            f("An orange is a bird."),
            f("Fire is colder than ice."),
            f("Umbrellas make people wet."),
            f("A letter goes in a teapot."),
            f("A baker bakes shoes."),
            f("The moon is made of wool."),
            f("People comb their hair with hammers."),
            f("Summer beaches are deep in snow."),
            f("Farmers grow cars in fields."),
            f("A mirror plays loud music."),
            f("Dogs have six legs."),
            f("Apples grow under the sea."),
            f("Bread is sliced with a clock."),
            f("Birds have fur and fins."),
            f("Letters are written with a spoon."),
            f("Coffee grows on the moon."),
            f("Hats are worn on feet."),
            f("Trees grow from stones."),
            f("The sea is made of sugar."),
            f("Cars run on orange juice."),
            f("Bees make bricks for houses."),
        )

    private val POLISH =
        listOf(
            t("Ryby pływają w wodzie."),
            t("Śnieg jest zimny."),
            t("Ptaki mają pióra i skrzydła."),
            t("Słońce wschodzi rano."),
            t("Chleb piecze się w piekarniku."),
            t("Krowy dają mleko."),
            t("Tydzień ma siedem dni."),
            t("Cytryny są kwaśne."),
            t("Drzewa rosną z nasion."),
            t("Deszcz pada z chmur."),
            t("Samochód potrzebuje paliwa."),
            t("Pszczoły robią miód."),
            t("Psy lubią gonić piłkę."),
            t("Lód topnieje w cieple."),
            t("Zegar pokazuje godzinę."),
            t("Jabłka rosną na drzewach."),
            t("Buty nosi się na stopach."),
            t("Morska woda jest słona."),
            t("Kluczem otwiera się zamek."),
            t("Trawa jest zwykle zielona."),
            t("Dzieci chodzą do szkoły."),
            t("Zupę je się łyżką."),
            t("Zima jest zimniejsza od lata."),
            t("Pilot prowadzi samolot."),
            t("Kot ma długie wąsy."),
            t("Książka składa się ze stron."),
            t("Rower ma dwa koła."),
            t("Kawę często pije się gorącą."),
            t("Gwiazdy świecą w nocy."),
            t("Lekarz pomaga chorym ludziom."),
            t("Pomarańcza jest owocem."),
            t("Ogień daje ciepło."),
            t("Na krześle się siedzi."),
            t("Góry są wyższe od pagórków."),
            t("Parasol chroni przed deszczem."),
            t("Konie szybko biegają."),
            t("List wkłada się do koperty."),
            t("Mleko jest białe."),
            t("Żaby potrafią skakać."),
            t("Piekarz piecze chleb."),
            t("Świeca daje światło."),
            t("Księżyc krąży wokół Ziemi."),
            t("Kaczki pływają po stawie."),
            t("Rękawiczki grzeją ręce."),
            t("Pociąg jedzie po torach."),
            t("Marchew rośnie w ziemi."),
            t("Młotkiem wbija się gwoździe."),
            t("Latem dni są długie."),
            t("Sowy polują nocą."),
            t("Łódki unoszą się na wodzie."),
            t("Herbatę parzy się wrzątkiem."),
            t("Fortepian ma klawisze."),
            t("Owce mają gęstą wełnę."),
            t("Drewno pochodzi z drzew."),
            t("Lustro odbija twarz."),
            t("Dojrzałe banany są żółte."),
            t("Rolnicy uprawiają zboże."),
            t("Wiatr porusza liśćmi."),
            t("W czajniku gotuje się wodę."),
            t("Nożyczkami tnie się papier."),
            f("Ryby wspinają się na drzewa."),
            f("Śnieg jest gorący."),
            f("Krowy latają nad domami."),
            f("Słońce wschodzi o północy."),
            f("Chleb piecze się w lodówce."),
            f("Tydzień ma dziesięć dni."),
            f("Cytryny smakują jak czekolada."),
            f("Deszcz pada z ziemi do góry."),
            f("Węże robią miód."),
            f("Lód zamarza w gorącym piekarniku."),
            f("Buty nosi się na rękach."),
            f("Zupę je się kluczem."),
            f("Trawa jest zwykle fioletowa."),
            f("Rower ma dziewięć kół."),
            f("Gwiazdy świecą tylko w południe."),
            f("Góry są niższe od kałuż."),
            f("Konie mieszkają na dnie morza."),
            f("Mleko jest jaskrawo niebieskie."),
            f("Żaby mówią po francusku."),
            f("Świece ochładzają pokój."),
            f("Kaczki są zrobione z kamienia."),
            f("Rękawiczki nosi się na uszach."),
            f("Pociąg płynie po niebie."),
            f("Marchew rośnie na chmurach."),
            f("Sowy czytają gazety."),
            f("Łódki jeżdżą po autostradzie."),
            f("Herbatę parzy się piaskiem."),
            f("Fortepian jest owocem."),
            f("Owce mają długie trąby."),
            f("Drewno robi się ze szkła."),
            f("Dojrzałe banany są niebieskie."),
            f("Wiatr jest rodzajem sera."),
            f("Czajnik zamraża wodę."),
            f("Kot znosi jajka w gnieździe."),
            f("Książki są zrobione z zupy."),
            f("Krzesło służy do pływania."),
            f("Dzieci jeżdżą do szkoły na wielorybach."),
            f("Zima jest cieplejsza od lata."),
            f("Pilot lata wanną."),
            f("Pomarańcza jest ptakiem."),
            f("Ogień jest zimniejszy od lodu."),
            f("Parasol moczy ludzi."),
            f("List wkłada się do czajnika."),
            f("Piekarz piecze buty."),
            f("Księżyc jest zrobiony z wełny."),
            f("Młotkiem czesze się włosy."),
            f("Latem na plaży leży gruby śnieg."),
            f("Rolnicy uprawiają samochody."),
            f("Lustro gra głośną muzykę."),
            f("Psy mają sześć nóg."),
            f("Jabłka rosną na dnie morza."),
            f("Chleb kroi się zegarem."),
            f("Ptaki mają futro i płetwy."),
            f("Listy pisze się łyżką."),
            f("Kawa rośnie na Księżycu."),
            f("Czapki nosi się na stopach."),
            f("Drzewa rosną z kamieni."),
            f("Morze jest zrobione z cukru."),
            f("Samochody jeżdżą na soku pomarańczowym."),
            f("Pszczoły robią cegły."),
        )
}
