"""Generate the estimated location of every time zone, from tzdata (ADR-0013 §5).

A schedule that follows the sun needs a place, and the only place Gloam has without asking is the
phone's time zone. tzdata records a principal location for each zone, and this script turns those
records into a Kotlin table. Every figure comes from IANA's files, and the files are public domain.

    python3 scripts/gen_zone_locations.py > app/src/main/java/app/gloam/shade/ZoneLocations.kt

Regenerate when tzdata adds or renames zones, and take the whole file.

**Three sources, in this order, and the order matters:**

1. `zone.tab`, one principal location per zone per country. It is listed first because tzdata
   2022 onward merged zones that have agreed since 1970 into links, and `zone1970.tab` lists only the
   survivor. From that file alone, `Europe/Oslo` would be a link to `Europe/Berlin`, and an Oslo phone
   would get a summer sunset more than an hour early. `zone.tab` still lists Oslo at Oslo.
2. `zone1970.tab`, for any zone the first file does not list.
3. The `L` (link) lines in `tzdata.zi`, so an old name such as `Poland` or `Asia/Calcutta`
   gets its target's location. A phone can still report such a name. Links to zones with no location,
   such as `Etc/UTC`, are left out, and a zone missing from the table falls back to the fixed times.

The default directory is the host's `/usr/share/zoneinfo`. Pass another directory as the only
argument to generate from a different tzdata release.
"""
import re
import sys
from pathlib import Path

PACKAGE = "app.gloam"  # the Kotlin package root; bootstrap.py rewrites this

COORDINATES = re.compile(r"^([+-])(\d{2})(\d{2})(\d{2})?([+-])(\d{3})(\d{2})(\d{2})?$")


def degrees(sign, d, m, s):
    value = int(d) + int(m) / 60 + (int(s) if s else 0) / 3600
    return -value if sign == "-" else value


def parse_coordinates(text):
    match = COORDINATES.match(text)
    if not match:
        sys.exit(f"unreadable coordinates: {text}")
    lat_sign, lat_d, lat_m, lat_s, lon_sign, lon_d, lon_m, lon_s = match.groups()
    # Two decimals is about a kilometre, far below what moves a sunset by a minute.
    return round(degrees(lat_sign, lat_d, lat_m, lat_s), 2), round(degrees(lon_sign, lon_d, lon_m, lon_s), 2)


def read_tab(path):
    rows = {}
    for line in path.read_text().splitlines():
        if not line or line.startswith("#"):
            continue
        fields = line.split("\t")
        rows[fields[2]] = parse_coordinates(fields[1])
    return rows


def read_links(path):
    links = {}
    for line in path.read_text().splitlines():
        if line.startswith("L "):
            _, target, alias = line.split()
            links[alias] = target
    return links


def main():
    zoneinfo = Path(sys.argv[1] if len(sys.argv) > 1 else "/usr/share/zoneinfo")
    version = (zoneinfo / "tzdata.zi").read_text().splitlines()[0].removeprefix("# version ").strip()

    locations = read_tab(zoneinfo / "zone.tab")
    for zone, place in read_tab(zoneinfo / "zone1970.tab").items():
        locations.setdefault(zone, place)

    links = read_links(zoneinfo / "tzdata.zi")
    for alias, target in links.items():
        # A link can point at another link. Follow the chain, and stop if it loops.
        seen = {alias}
        while target in links and target not in seen:
            seen.add(target)
            target = links[target]
        if target in locations and alias not in locations:
            locations[alias] = locations[target]

    out = [
        f"package {PACKAGE}.shade",
        "",
        "import java.time.ZoneId",
        "",
        f"// GENERATED by scripts/gen_zone_locations.py from tzdata {version}. Regenerate it; never hand-edit.",
        "//",
        "// Each zone's principal location, from zone.tab, then zone1970.tab, then tzdata's links for",
        "// old names. The script's docstring says why that order matters.",
        "",
        "/**",
        " * The **estimated location** (CONTEXT.md) for [zone]: the principal location tzdata records for",
        " * it, or `null` for a zone with none, such as `UTC` or a fixed offset.",
        " *",
        " * Kotlin note: the map below is a top-level `val`, so it is built when this file's class is",
        " * first loaded, which is the first call here, not app start. That makes it lazy without `by lazy`.",
        " */",
        "fun estimatedLocation(zone: ZoneId): Coordinates? = ZONE_LOCATIONS[zone.id]",
        "",
        "private val ZONE_LOCATIONS: Map<String, Coordinates> =",
        "    mapOf(",
    ]
    for zone in sorted(locations):
        lat, lon = locations[zone]
        out.append(f'        "{zone}" to Coordinates({lat!r}, {lon!r}),')
    out.append("    )")
    print("\n".join(out))


if __name__ == "__main__":
    main()
